// 《37% 法则：看多少家公司，才该下手》—— F23 可运行模拟 × F22 编年史，横屏无口播知识短片
// 事实核对（2026-10-09）：Flood 1949 讲座提出"未婚妻问题"，Lindley 1961 首次刊出；最优策略 = 先看 n/e≈37% 再选，成功率 1/e≈36.8%；
// 开普勒 1611–1613 考虑 11 位候选人，想选第 4 位被拒，娶了第 5 位；"只求平均名次"最优策略期望名次 ≈ 3.8695（Chow, Moriguti, Robbins & Samuels 1964）。
const E = Math.E; // storyboard 里不能放函数（defaultProps 走 JSON）：曲线用 fn: 'xlnx' 查表
export default {
  id: 'rule37', title: '37% 法则', sub: '看多少家公司，才该下手', tone: 'brown', duration: 158,
  acts: [12, 30, 56, 84, 118, 140],
  bobby: {at: 22.5, hold: 90, say: '整理'},
  captions: [
    {at: 0.3, text: '【37%】，也算出了：你该看到第几家'},
    {at: 4.6, text: '假设你要在 100 家公司里选一家'},
    {at: 7.2, text: '一家一家看，看过的不能回头'},
    {at: 9.6, text: '你只想要【最好】的那一家'},
    {at: 12.5, text: '这道题，数学已经算了 70 多年'},
    {at: 15.5, text: '它叫【最优停止】问题'},
    {at: 19.5, text: '1949 年，数学家弗勒德第一次提出它'},
    {at: 22.6, text: '用 Bobby AI 把 100 家公司的财报摆成一把【标尺】'},
    {at: 26, text: '先看前 【37%】，一家都不选'},
    {at: 28.3, text: '之后遇到比前面都好的，立刻出手'},
    {at: 30.6, text: '把这个游戏重玩【一百万遍】'},
    {at: 33.6, text: '选中最好那家的概率，画成一条线'},
    {at: 37.2, text: '最高点在 36.8%，也就是 【1/e】'},
    {at: 40.8, text: '这就是 37% 的来历'},
    {at: 44.6, text: '但注意，这个最高点本身只有 37%'},
    {at: 48, text: '也就是说，做对一切'},
    {at: 50.6, text: '仍有 【63%】 的概率错过最好的'},
    {at: 53.6, text: '最优解，自带遗憾'},
    {at: 56.6, text: '天文学家开普勒，亲身试过这道题'},
    {at: 60, text: '1611 年丧偶后，他考虑了 【11】 位候选人'},
    {at: 63.2, text: '犹豫太久，想选的第 4 位嫁给了别人'},
    {at: 66.6, text: '最后娶了第 5 位，相伴一生'},
    {at: 70.6, text: '回到选公司'},
    {at: 73, text: '100 家里，先认真看完 37 家'},
    {at: 76, text: '不下手，只做一件事：【立标尺】'},
    {at: 79.6, text: '第 38 家起，一旦有超过标尺的，出手'},
    {at: 82.2, text: '这叫：先看，再跳'},
    {at: 84.6, text: '如果你不非要最好，只要【足够好】'},
    {at: 88, text: '数学给出另一个答案'},
    {at: 91, text: '最优策略下，平均能拿到第 3.87 名'},
    {at: 94.6, text: '放下完美，结果反而更稳'},
    {at: 98.6, text: '有人会问：我哪知道总共有多少家？'},
    {at: 101.4, text: '那就用【时间】代替数量'},
    {at: 103.4, text: '给自己一个月，前 11 天只看不买'},
    {at: 104.6, text: '所以这道题教的是三件事'},
    {at: 107.6, text: '第一，观察期不是浪费'},
    {at: 110.6, text: '第二，标尺立好就要敢出手'},
    {at: 114, text: '第三，做对一切也可能遗憾，这是数学的上限'},
    {at: 118.6, text: '数学替你算好了遗憾的上限'},
    {at: 122.6, text: '剩下的，交给【勇气】'},
    {at: 126, text: '致所有还在观察期的人'},
    {at: 130.6, text: '这把标尺，可以让 Bobby AI 帮你立'},
    {at: 134.6, text: '问它一句，几十家公司并排看'},
    {at: 140.6, text: '本片为数学模型演示，不构成投资建议'},
    {at: 145, text: '参考资料见屏幕'},
  ],
  scenes: [
    {at: 0, dur: 4.5, type: 'poster', props: {big: '37%', line1: '看多少家公司，才该下手', line2: 'VIBE 知识大赏 · 最优停止', date: '2026 · 10 · 09'}},
    {at: 4.5, dur: 7.5, type: 'cards', props: {n: 10, look: 0}, hud: {title: '规则'}},
    {at: 12, dur: 7, type: 'title', props: {title: '37% 法则', sub: '看多少家公司，才该下手'}},
    {at: 19, dur: 11, type: 'doc', props: {heading: '1949 · PRINCETON', lines: ['Merrill Flood 在一次讲座里提出', '“未婚妻问题” The Fiancée Problem', {t: 'n / e ≈ 37%', big: true}]}, hud: {year: '1949'}, cite: 'Flood 1949 · Lindley 1961'},
    {at: 30, dur: 14, type: 'curve', props: {fn: 'xlnx', peakX: 1 / E, peakText: '36.8% = 1/e', xText: '先看多少比例，再出手 →', dur: 60}, hud: {title: '一百万次模拟'}},
    {at: 44, dur: 12, type: 'big', props: {value: 63, suffix: '%', label: '完美执行，仍然错过', color: 'down', burst: true, delay: 4}, hud: {title: '遗憾的上限'}},
    {at: 56, dur: 14, type: 'doc', props: {heading: '1611–1613 · PRAGUE', lines: ['开普勒丧偶后，考虑了 11 位候选人', '犹豫中，想选的第 4 位嫁给了别人', {t: '最后娶了第 5 位', big: true}], rot: 1}, hud: {year: '1613'}, cite: 'Kepler, letters 1613'},
    {at: 70, dur: 14, type: 'cards', props: {n: 10, look: 4, pick: 6}, hud: {title: '先看，再跳'}},
    {at: 84, dur: 14, type: 'compare', props: {left: {title: '只求最好', lines: ['成功率 36.8%', '错过率 63.2%', '很可能两手空空']}, right: {title: '只求足够好', lines: ['目标：平均名次尽量靠前', '最优策略 · 平均第 3.87 名', '放下完美，结果更稳'], color: '#5FA86E'}}, cite: 'Chow · Moriguti · Robbins · Samuels 1964'},
    {at: 98, dur: 6, type: 'steps', props: {steps: [{year: '第 1 天', text: '开始看'}, {year: '第 11 天', text: '标尺立好'}, {year: '第 30 天', text: '截止'}], active: 1}, hud: {title: '总量未知时'}},
    {at: 104, dur: 14, type: 'list', props: {items: ['看满 37%，一家都不买', '标尺立好，敢跳', '做对一切，也接受错过']}, hud: {title: '三件事'}},
    {at: 118, dur: 12, type: 'quote', props: {text: '遗憾，有上限。\n勇气，没有。', sub: '致所有还在观察期的人'}},
    {at: 130, dur: 10, type: 'doc', props: {heading: '资料由 BOBBY AI 整理', lines: ['该问 Bobby：', '“把这 37 家公司的营收增速并排列出来”', '“哪一家的毛利率连续 5 年上升”'], rot: -0.6, logo: 'logos/BobbyAI_icon.png'}},
    {at: 140, dur: 12, type: 'ref', props: {items: ['Flood, M. M. (1949). The Fiancée Problem（讲座）', 'Lindley, D. V. (1961). Dynamic programming and decision theory. Applied Statistics', 'Chow, Moriguti, Robbins & Samuels (1964). Optimal selection based on relative rank. Israel J. Math.', 'Ferguson, T. S. (1989). Who solved the secretary problem? Statistical Science', 'Christian, B. & Griffiths, T. (2016). Algorithms to Live By']}},
    {at: 152, dur: 6, type: 'title', props: {title: '37% 法则', sub: 'VIBE 知识大赏', by: '数学模型演示 · 不构成投资建议 · Bobby AI 出品'}},
  ],
};
