// 《幸存者偏差：榜单上的基金，都是飞回来的飞机》—— F02 侦探反转，横屏无口播知识短片
// 事实核对（2026-10-09）：Wald 1943 SRG 备忘录（返航机弹孔 → 装甲加在没弹孔处）；SPIVA 美国 2024 年末：20 年前的大盘股基金只有约 33% 存活、约 2/3 合并或清盘，
// 约 92% 跑输标普 500（含已清盘）；1987 Whitney & Mehlhaff（JAVMA）纽约动物医疗中心 132 只坠楼猫、90% 存活；Wald 1938 逃离维也纳、家人多死于奥斯维辛、1950 年印度空难。
export default {
  id: 'survivor', title: '幸存者偏差', sub: '榜单上的基金，都是飞回来的飞机', tone: 'navy', duration: 152,
  acts: [12, 45, 70, 98, 124, 134],
  bobby: {at: 7.6, hold: 90, say: '整理'},
  disclaimer: '内容仅供科普 · 基金有风险 · 不构成投资建议',
  captions: [
    {at: 0.3, text: '20 年前的 100 只基金，今天只剩 【33】 只'},
    {at: 4.6, text: '剩下的 33 只，每一只都有 20 年业绩'},
    {at: 7.6, text: '用 Bobby AI 把 2004 年的基金名单拉出来一数'},
    {at: 10.2, text: '你看不见的那 67 只，去哪了？'},
    {at: 12.5, text: '先讲一个 1943 年的故事'},
    {at: 15.5, text: '它和你的基金榜单，是同一件事'},
    {at: 19.5, text: '1943 年，美军统计返航轰炸机上的弹孔'},
    {at: 23, text: '机翼和机尾密密麻麻，发动机几乎没有'},
    {at: 26.5, text: '军方的结论：给弹孔多的地方加装甲'},
    {at: 29.6, text: '如果是你，装甲加在哪？先想 3 秒'},
    {at: 33.5, text: '统计学家【瓦尔德】说：反了'},
    {at: 36.5, text: '发动机被打中的飞机，根本没飞回来'},
    {at: 40, text: '你统计的，只是【幸存者】'},
    {at: 42.6, text: '装甲，要加在没有弹孔的地方'},
    {at: 45.5, text: '回到基金榜单'},
    {at: 48, text: '标普道琼斯每年统计一次：20 年前的基金'},
    {at: 51.6, text: '大约 【三分之二】 已经合并或清盘'},
    {at: 55, text: '它们的业绩，不会出现在任何榜单上'},
    {at: 58.5, text: '再往下看一层'},
    {at: 61.5, text: '20 年里跑赢标普 500 的基金'},
    {at: 64.6, text: '只有大约 【8%】'},
    {at: 67.5, text: '你在榜单上看到的，是幸存者里的幸存者'},
    {at: 70.5, text: '同一个错觉，到处都是'},
    {at: 73.5, text: '1987 年纽约，132 只从高楼掉下的猫'},
    {at: 76.5, text: '数据显示：楼层越高，伤反而越轻'},
    {at: 79.6, text: '真相是：当场摔死的猫，没人送去医院'},
    {at: 82.2, text: '送到医院的，本来就是幸存者'},
    {at: 84.6, text: '生活里也一样'},
    {at: 87, text: '辍学成首富的故事，没算辍学失败的人'},
    {at: 90.6, text: '老房子更结实？塌了的那些早没了'},
    {at: 93.6, text: '十年十倍的基金，背后是一千只没活到今天的'},
    {at: 98.6, text: '最后说回瓦尔德'},
    {at: 101.6, text: '1938 年他逃离纳粹，家人几乎都没能逃出来'},
    {at: 105, text: '1950 年，他在印度死于一场空难'},
    {at: 108.5, text: '教人看没回来的飞机的人，自己也成了没回来的那一个'},
    {at: 112.6, text: '所以下次有人给你看榜单'},
    {at: 116, text: '记得问一句：'},
    {at: 118.6, text: '【没回来的在哪里？】'},
    {at: 124.6, text: '问活下来的，也问没活下来的'},
    {at: 128.6, text: '这三句话，可以直接问 Bobby AI'},
    {at: 134.6, text: '本片为科普，基金有风险，不构成投资建议'},
    {at: 139, text: '参考资料见屏幕'},
  ],
  scenes: [
    {at: 0, dur: 4.5, type: 'poster', props: {variant: 'left', big: '33%', line1: '榜单上的基金，\n都是飞回来的飞机', line2: 'VIBE 知识大赏 · 幸存者偏差', date: '2026 · 10 · 09'}},
    {at: 4.5, dur: 7.5, type: 'cards', props: {n: 10, look: 0, lostAfter: 4, labels: ['基金 A', '基金 B', '基金 C', '基金 D', '基金 E', '基金 F', '基金 G', '基金 H', '基金 I', '基金 J']}, hud: {title: '2004 → 2024'}},
    {at: 12, dur: 7, type: 'title', props: {title: '幸存者偏差', sub: '榜单上的基金，都是飞回来的飞机'}},
    {at: 19, dur: 14, type: 'plane', props: {holes: 110}, hud: {year: '1943'}, cite: 'Wald 1943 · Statistical Research Group, Columbia'},
    {at: 33, dur: 12, type: 'plane', props: {holes: 110, highlightEmpty: true, still: false}, hud: {year: '1943', title: '瓦尔德'}, cite: 'Mangel & Samaniego 1984 · JASA'},
    {at: 45, dur: 13, type: 'doc', props: {heading: 'SPIVA U.S. · YEAR-END 2024', lines: ['20 年前的美国大盘股基金', '活到今天的：约 33%', {t: '约 2/3 已合并或清盘', big: true}]}, hud: {year: '2024'}, cite: 'S&P Dow Jones Indices · SPIVA'},
    {at: 58, dur: 12, type: 'bars', props: {bars: [{label: '20 年跑赢指数', value: 8, color: '#5FA86E'}, {label: '活着但跑输', value: 25}, {label: '已合并 / 清盘', value: 67, color: '#C8463A'}], fmt: 'pct', maxV: 80}, hud: {title: '100 只基金的 20 年'}, cite: 'SPIVA U.S. Year-End 2024（已清盘计入跑输）'},
    {at: 70, dur: 14, type: 'doc', props: {heading: '1987 · NEW YORK · JAVMA', lines: ['动物医疗中心统计 132 只高空坠落的猫', '90% 活了下来', {t: '7 层以上，受伤反而更轻？', big: true}], rot: 1}, hud: {year: '1987'}, cite: 'Whitney & Mehlhaff 1987'},
    {at: 84, dur: 14, type: 'list', props: {items: ['辍学的首富', '更结实的老房子', '十年十倍的基金'], mark: '✗'}, hud: {title: '三张幸存者卡片'}},
    {at: 98, dur: 14, type: 'doc', props: {heading: 'ABRAHAM WALD · 1902–1950', lines: ['1938 年逃离维也纳', '家人几乎全部死于奥斯维辛', {t: '1950 年，死于印度一场空难', big: true}], rot: -0.8}, hud: {year: '1950'}},
    {at: 112, dur: 12, type: 'quote', props: {text: '下次有人只给你看活下来的，\n记得问一句：没回来的在哪里？'}},
    {at: 124, dur: 10, type: 'doc', props: {heading: '该问 BOBBY AI', lines: ['“这只基金 2018 和 2022 年表现如何”', '“这个策略回测时剔除了多少只已清盘基金”', '“同类基金 10 年存活率是多少”'], rot: -0.6, logo: 'logos/BobbyAI_icon.png'}},
    {at: 134, dur: 12, type: 'ref', props: {items: ['Wald, A. (1943). A Method of Estimating Plane Vulnerability Based on Damage of Survivors. SRG, Columbia University', 'S&P Dow Jones Indices (2025). SPIVA U.S. Scorecard, Year-End 2024', 'Whitney, W. O. & Mehlhaff, C. J. (1987). High-rise syndrome in cats. JAVMA 191(11)', 'Mangel, M. & Samaniego, F. J. (1984). Abraham Wald’s Work on Aircraft Survivability. JASA 79(386)']}},
    {at: 146, dur: 6, type: 'title', props: {title: '幸存者偏差', sub: 'VIBE 知识大赏', by: '科普内容 · 基金有风险 · 不构成投资建议 · Bobby AI 出品'}},
  ],
};
